config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :home do
    collection do
      post :is_prime_number
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def is_prime_number
    @result  = PrimeNumberService.new(params[:number].to_i).call
    respond_to do |format|
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Prime Number</h1>
<%= form_tag is_prime_number_home_index_path, method: :post, remote: true do %>
	<%= number_field_tag "number",nil, required: true%>
	<%= submit_tag "Check Number", class: "submit-btn", id: "submit-btn"%>
<%end%>

app/views/home/is_prime_number.js.erb
<%if @result%>
 	toastr.success('Success, this is a prime number.')
<%else%>
	toastr.error('Error, this is not a prime number.')
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTest</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  	<% unless flash.empty? %>
	  <script type="text/javascript">
	      <% flash.each do |f| %>
	      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
	     	 toastr['<%= type %>']('<%= f[1] %>');
	      <% end %>
	  </script>
	<% end %>
    <%= yield %>
  </body>
</html>